exp:
  name: "CIFAR100B0S10_DER_wo_mask"
  savedir: "./logs"
  tensorboard_dir: "./tensorboard"
  debug: False


#Model Cfg
model: "incmodel"
#b0:'preact_resnet18'
#b50: 'resnet18'
convnet: 'preact_resnet18' #resnet18
train_head: 'softmax'
infer_head: 'softmax'
channel: 64
use_bias: False

der: True
use_aux_cls: True
aux_n+1: True
distillation: "none"
temperature: 2

reuse_oldfc: False
weight_normalization: False
val_per_n_epoch: -1 # Validation Per N epoch. -1 means the function is off.
save_ckpt: True
save_mem: True
load_mem: False

#Optimization;Training related
task_max: 10
lr_min: 0.00005
lr: 0.1 #  0.0005# # 0.0003 2 0.001
weight_decay: 0.0005 #0.0005 #0.00001 0.0005
dynamic_weight_decay: False
scheduler: 'multistep' #'multistep' cos
scheduling:
  - 60
  - 120
  - 160
  - 180
lr_decay: 0.1 #0.1 # LUCIR 0.1 our 0.2 LR LR multiplied by it
warmup: True
warmup_epochs: 20
optimizer: "sgd" #LUCIR "sgd" our adam
epochs: 220 #Number of epochs per task our 70
resampling: False

postprocessor:
  enable: False
  type: 'wa' #'bic', 'wa'
  epochs: 30
  batch_size: 128
  lr: 0.1
  scheduling:
    - 60
    - 90
    - 120
  lr_decay_factor: 0.1
  weight_decay: 0.0005

decouple:
  enable: True
  epochs: 30
  fullset: False
  lr: 0.1
  scheduling:
    - 15
  lr_decay: 0.1
  weight_decay: 0.0005
  temperature: 1.0

pretrain:
  epochs: 200
  lr: 0.1
  scheduling:
    - 60
    - 120
    - 160
  lr_decay: 0.1
  weight_decay: 0.0005


# Dataset Cfg
dataset: "imagenet100" #'imagenet100', 'cifar100'
trial: 0
increment: 10
batch_size: 256
workers: 16
validation: 0 # Validation split (0. <= x <= 1.)
random_classes: False #Randomize classes order of increment
start_class: 0 # number of tasks for the first step, start from 0.
start_task: 0
max_task: # Cap the number of task

#Memory
coreset_strategy: "iCaRL" #"iCaRL"  ,random, inccore, k-nearest-mean
mem_size_mode: "uniform_fixed_total_mem" #uniform_fixed_per_cls, uniform_fixed_total_mem, dynamic_fixed_per_cls
memory_size: 2000 # Max number of storable examplars
fixed_memory_per_cls: 30 # the fixed number of exemplars per cls

# Misc
device: 0 #GPU index to use, for cpu use -1
seed: 1993
